on:
  pull_request:
    paths-ignore:
      - "**/*.json"
      - "**/*.md"
      - "**/*.png"
      - "**/*.jpg"
      - "**/*.jpeg"
      - "**/*.gif"
      - "**/*.svg"
      - ".gitgnore"

jobs:
  call_code_review:
    uses: umzug-meister/workflows/.github/workflows/ai-review.yml@main
    permissions:
      contents: read
      pull-requests: write
