name: "Build pull request"

on:
  pull_request:

jobs:
  build-pr:
    name: Build PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install modules
        run: npm ci

      - name: Build App
        run: npm run build
        env:
          VITE_BACKEND_URL: ${{ secrets.BACKEND_URL }}
