name: "Build pull request"

on:
  pull_request:

jobs:
  build-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install modules
        run: npm ci

      - name: Build App
        run: npm run build
        env:
          VITE_BASE_URL: ${{ secrets.BACKEND_URL }}
