on:
  push:
    branches:
      - "main"

name: 🚀 Deploy um-express-form
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install modules
        run: npm install

      - name: Build app
        run: npm run build

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          protocol: ftps
          port: 22
          local-dir: ${{ github.workspace }}/dist/
          server-dir: /134479_umzug___ruck_zuck/wordpress/um-forms/express/
          # exclude: |
          #   index.html
