name: "Deploy um-express-form"

on:
  push:
    branches:
      - "main"

jobs:
  ci-build-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install modules
        run: npm ci

      - name: Build App
        run: npm run build
        env:
          VITE_BASE_URL: ${{ secrets.BACKEND_URL }}

      - name: Configure S3
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: "eu-central-1"

      - name: Upload to aws
        run: aws s3 sync ./dist s3://um-express-form
