on:
  push:
    branches:
      - "main"

name: 🚀 Deploy um-express-form
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install modules
        run: npm install

      - name: Build app
        run: npm run build
        env:
          VITE_BACKEND_URL: ${{ secrets.BACKEND_URL }}
          BASE_URL: "/um-forms/express/"

      - name: Sync files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          sftp_only: true
          port: 22
          local_path: "./dist/*"
          remote_path: "/134479_umzug___ruck_zuck/wordpress/um-forms/express"
